### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by midknight41** [midknight41/map-factory#10]
- Better descriptions
- Summary of features
- Define best way to deal with multiple input objects.

**Comment by blacksun1** [comment]
Anything left in for this that you feel needs to be done? It's feeling pretty done for me.

**Comment by midknight41** [comment]
I think it still needs some love. It's too sparse and lacks good narrative. I'll make some improvements over the next little while.

**Comment by blacksun1** [comment]
It probably needs seem some pretty pictures. ;)

**Comment by midknight41** [comment]
:stuck_out_tongue:

**Comment by midknight41** [comment]
Updated Docs. That's good enough for me for now.
