### ISSUE TITLE
Proposals- Pipeline Transformation

### ISSUE THREAD

**Issue by simranjeet2589** [midknight41/map-factory#100]
Following are some proposals for pipeline transformations:-

- sortAsc : Will sort the array in ascending order and returns the array
```
.map("foo").sortAsc();
// or
.map("foo").sortAsc(() => 1) // by passing in a comparator to sort
```

- sortDsc: Will sort the array in descending order and returns the array
```
.map("foo").sortDsc();
// or
.map("foo").sortDsc(() => 1) // by passing in a comparator to sort
```

- groupBy: Will group the results in the array and returns an object with the grouped property as key.
```
.map("foo").groupBy(() => 1); // by passing in the function to be utilised as an iterator for grouping.
```

@midknight41 : what are your thoughts on these?

**Comment by midknight41** [comment]
Can you give a more practical example for groupBy?

**Comment by simranjeet2589** [comment]
Categorising a large set of array as per a key. For example: we have an array of object with property type and i would like to distinguish the objects in the array using the property.

```
const files = [{type: "Image"}, {"type": video}];

// desired output could be
{
  "image": [],
  "video": []
}
```

**Comment by simranjeet2589** [comment]
Yes, the property use for grouping will become the key to identify the group and array will have all the matched items to that key.

Thanks for ignoring syntax issues. It is hard to type code from phone. ☺️

**Comment by simranjeet2589** [comment]
@midknight41 should i start looking into the enhancements?

**Comment by simranjeet2589** [comment]
sounds good to me. I will start with sort.
