### ISSUE TITLE
Field with getter function is not mapped

### ISSUE THREAD

**Issue by apricote** [midknight41/map-factory#102]
When trying to map a field with a getter property, map-factory does not properly return the field.

### Reproduction

```javascript
const map = require("map-factory")();

const objectWithGetter = {
  get field() {
    console.log("getter called");
    return "foo";
  }
};

map("field");
console.log("mapped:", map.execute(objectWithGetter));
```

### Expected Result
Console Output
```
executed getter
mapped: { field: "foo" }
```

### Actual Result
Console Output
```
executed getter
mapped: {}
```

**Comment by simranjeet2589** [comment]
I tried your version of the code on runkit, looks like it is returning the right response.

![image](https://user-images.githubusercontent.com/12469462/46247280-01dbe600-c401-11e8-9c07-2c946ab52ff6.png)

@apricote could you please verify it again or post out the steps to replicate the issue?

**Comment by apricote** [comment]
You are correct. It looks like my problem was caused by something else (see #104), and the repro case I posted was too simple to contain my actual bug.

I should test my bug reports more thoroughly.. 

Thanks for your effort.
