### ISSUE TITLE
How to set null value for non existing property

### ISSUE THREAD

**Issue by Hasan-git** [midknight41/map-factory#125]
const source = {     
        "job": "Enchanter",
        "account": {          
          "email": "tim@enchanter.com"
        }
      };   
   
      mapper .map("account.mobile").always.to("mobile",()=> null);

      const actual = mapper.execute(source);
      console.log(actual) // => { }

where the expected object to be:  
{
  mobile: null
}

**Comment by midknight41** [comment]
There is (embarrassingly) an undocumented feature to deal with this use case. If you add a ? (See below) to the target name it signals the mapping to allow null as a value.

const source = {     
    "job": "Enchanter",
    "account": {          
      "email": "tim@enchanter.com"
    }
  };   

  mapper .map("account.mobile").always.to("mobile?",()=> null);

  const actual = mapper.execute(source);
  console.log(actual) // => {mobile: null}

You can also use the shorthand for this mapping if appropriate for your use case.

mapper.set("mobile?", null)

**Comment by Hasan-git** [comment]
Thank you @midknight41
