### ISSUE TITLE
TypeError: map_factory_1.default is not a function

### ISSUE THREAD

**Issue by santhoshsridhar0304** [midknight41/map-factory#127]
I'm gettting this error while working with typescript

`import createMapper from "map-factory";`

`const map = createMapper();`

`map("items[].items[].name")`
`  .to("[].salesOrderLines[].lineType")`
`  .set("[].salesOrderLines[].lineType", "Item");`

`const dest = map.execute(src);`

`console.log(dest);`
`

**Comment by singhs020** [comment]
HI @santhoshsridhar0304 ,

Just tried an example in code sandbox and looks like it is working. Please have a look at following. It prints out stuff in console.

[Map-factory-typescript](https://codesandbox.io/s/map-factory-typescriptv4-otx2w?file=/src/index.ts)

Can you please share some more details?
