### ISSUE TITLE
Reading the code with multiple readers feels a bit yucky.

### ISSUE THREAD

**Issue by midknight41** [midknight41/map-factory#13]
The code reads well when you do a single map:

```js

const map = new Mapper();

map("a").to("b");

const result = map.execute({a: "value"});

```
But not so good if you are using multiple mappers:

```js
const postMapper = new Mapper();
const authorMapper = new Mapper();

// does read very nice without 'map'
postMapper("text").to("user.text");
authorMapper("name").to("user.name");

const posts = postMapper.execute({"text": "value"});
const result = authorMapper.execute({"name": "Tim the Enchanter"}, posts);
```
It would read better if we also supported:

```js
const postMapper = new Mapper();
const authorMapper = new Mapper();

// does read very nice without 'map'
postMapper.map("text").to("user.text");
authorMapper.map("name").to("user.name");

const posts = postMapper.execute({"text": "value"});
const result = authorMapper.execute({"name": "Tim the Enchanter"}, posts);
```

**Comment by midknight41** [comment]
I've already done the code but am just finishing the docs.

**Comment by blacksun1** [comment]
If you are doing this change then it would also be good if the `to("")` method returns the mapper object (this) because then you could chain the calls.

```js
const postMapper = (new Mapper())
  .map("text").to("user.text")
  .map("description").to("user.description");
```

BTW, what happened to the createMapper() function?

```js
const postMapper = createMapper()
  .map("text").to("user.text")
  .map("description").to("user.description");
```

reads better to me.


Regards,

**Comment by blacksun1** [comment]
BTW, I would have structured your example more like

```js
const postMapper = new Mapper();
postMapper.map("text").to("user.text");

const authorMapper = new Mapper();
authorMapper.map("name").to("user.name");

const posts = postMapper.execute({"text": "value"});
const result = authorMapper.execute({"name": "Tim the Enchanter"}, posts);
```

I still think that the 

```js
const result = authorMapper.execute({"name": "Tim the Enchanter"}, posts);
```

would be better with a merge method. Having the source as the last parameter seems wrong as most API's I know use the destination parameter as the first one. So I would push for

```js
const posts = postMapper.execute({"text": "value"});
const result = authorMapper.merge(posts, {"name": "Tim the Enchanter"});
```

Regards,

**Comment by midknight41** [comment]
Sorry, I typed dumb. createMapper still there, no use of new on the public API. 

We are on the same page. I'm just exposing the default method additionally as a method on the mapper. Let's discuss chaining later.

**Comment by midknight41** [comment]
I'm not sure what you are on about about ```source``` being the second parameter. The signature is:

```execute(sourceForMapping, existingObjectThatYouWatchToAttachTheResultTo)```

**Comment by blacksun1** [comment]
Normally you merge into the first parameter.

So it would be `merge(existingObjectThatYouWatchToAttachTheResultTo, sourceForMapping)`.

**Comment by midknight41** [comment]
That would be **extremely** confusing to me. The implemented ```execute``` method takes source as its first parameter. Source shouldn't become the second parameter when you add the destination.

I'm also not keen on making unnecessary breaking changes. This would break an existing method a couple days after it was implemented.
