### ISSUE TITLE
Documentation code does not execute.

### ISSUE THREAD

**Issue by blacksun1** [midknight41/map-factory#17]
So, I wrote this: https://github.com/blacksun1/validate-markdown-code

And it found some issues.

I will fix them.

**Comment by midknight41** [comment]
Cool. The assert examples look nicer than the consol.log stuff.

**Comment by blacksun1** [comment]
Yeah, that is what I thought too. 

The `validate-markdown-code` code is horrendous at this stage, it was just a complete hack but the guts is there. I'll perfect it over the next couple of weeks and push it to NPM.

Closing this now.
