### ISSUE TITLE
always property not working as expected

### ISSUE THREAD

**Issue by simranjeet2589** [midknight41/map-factory#40]
Hi, 

In latest version of the map-factory, there is a support for calling transform even if its set to false at a global level. following is the code mentioned in docs:

```
const createMapper = require("map-factory");
 
const mapper = createMapper(options);
 
mapper
  .map("a").always.to("b")
```

This does not seems to work. Could you please verify this?

Regards
Simranjeet Singh

**Comment by midknight41** [comment]
Whoops. I apparently dreamed writing that code. All fixed. Shipped as ```v1.7.1```
