### ISSUE TITLE
If fieldname is not string, then it does not map

### ISSUE THREAD

**Issue by bharanidharan-k** [midknight41/map-factory#5]
the mapper always expects the fieldname to be string.
source JSON
         {country: 'PL'} 
if I try to map using map("country").to("country") then it does not map.

**Comment by midknight41** [comment]
I can't replicate that problem. Can I confirm this is what you are trying to do?

```js
const source = {
  country: "PL"
};

const expected = {
  "country": "PL"
};

const map = createMapper(source);

map("country").to("country");

const actual = map.execute();

console.log("COUNTRY", actual);

test.deepEqual(actual, expected);
test.done();
```

**Comment by bharanidharan-k** [comment]
It works fine. My sourcec generated by an api was incorrect. 
Hence, closing this issue.

**Comment by midknight41** [comment]
No worries. Be aware, I'm changing the interface slightly for v1. **source** is now supplied to ```map.execute()``` not the factory method which makes a lot more sense.

You can omit .to("country") if you aren't changing the field name or structure btw.

```js
const source = {
  country: "PL"
};

const expected = {
  "country": "PL"
};

const map = createMapper();

map("country").to("country");

const actual = map.execute(source);

console.log("COUNTRY", actual);

test.deepEqual(actual, expected);
test.done();
```

**Comment by bharanidharan-k** [comment]
I noticed it. Definitely makes sense :-)
