### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by mnguyen972** [midknight41/map-factory#57]
How would you map the source to the result below?  Any help would be appreciated.

Source:

Source = {
  "test": ["a","b","c"]
}

"a" maps to "johnny"
"b" maps to "mark"
"c" maps to "bobby"

Result = {
 "result": [
    {"test": "johnny"},
    {"test": "mark"},
    {"test": "bobby"}
]}

**Comment by midknight41** [comment]
You just need to use a transform like the below example. 

Sorry for the delay in responding. I've been away.

Hope that helps.

```js
const createMapper = require("map-factory");

const mapper = createMapper();
const nameLookup = new Map();

nameLookup.set("a", "johnny");
nameLookup.set("b", "mark");
nameLookup.set("c", "bobby");

mapper.map("test[]").to("result[].test", values => {

  // This is the normal map function...nothing to do with map-factory
  return values.map(value => {
    return nameLookup.get(value);
  });

});
```
