### ISSUE TITLE
alwaysSet not working for missing Array

### ISSUE THREAD

**Issue by apricote** [midknight41/map-factory#65]
Hello again,
I think I found a bug with the way `alwaysSet` interacts with a non existant array on the source object:

```javascript
const createMapper = require("map-factory");

const srcWorking = [{ name: "Peter" }, { name: "Stevie" }];
const srcBroken = [];

const mapper = createMapper({ alwaysSet: true });
mapper.map("[].name").to("names");

const mappedWorking = mapper.execute(srcWorking);
const mappedBroken = mapper.execute(srcBroken);

// Expected+Actual Result: { names: [ 'Peter', 'Stevie' ] }
console.log(mappedWorking);

// Expected Result: { names: [] }
// Actual Result: {}
console.log(mappedBroken);
```

As I understood the setting, it should __always__ set the target attribute, even if the source structure is not there at all:

> alwaysSet: boolean
> if true then nested structure will be created even if the source value was not available on the source object.
> - https://github.com/midknight41/map-factory#modify-default-behaviour

Anyway, kudos to you for providing this package and the quick support/fixes !

**Comment by midknight41** [comment]
Hmmmm...a slight change to your mapper will yield the desired result:

```js
const mapper = createMapper({ alwaysSet: true });
mapper.map("[].name").to("names[]");
```
I'll ponder if this is a bug. The *nested* word is key here. The way the internal set works is to create structure recursively. Here there is no nesting as you are targeting the route element.

**Comment by apricote** [comment]
You are right, the proposed change works.

It confused me a bit because with an ordinary `map` I also get an empty array from an empty input array, so I expected it to be kinda analogues.

And also the nested structure up to the last point gets created correctly:

```javascript
const createMapper = require("map-factory");

const mapper = createMapper({ alwaysSet: true });
mapper.map("[].name").to("names.values");

const mapped = mapper.execute([]);

// { names: {} }
console.log(mapped);
```

Just the last element is missing, but that is also the behaviour for objects with missing source key:

```javascript
const createMapper = require("map-factory");

const src = {};

const mapper = createMapper({ alwaysSet: true });
mapper.map("name.value").to("name.value");

const mapped = mapper.execute(src);

// { names: {} }
console.log(mapped);
```

So there seems to be no bug.

**Comment by midknight41** [comment]
Glad that works for you.

The consistency is that the last specified key  does not appear in the target object. In "names.value" the "value" key is absent. The fix I provided works because "[]"  is considered a key and map-factory can infer you want an array object.
