### ISSUE TITLE
Convert code to Babel?

### ISSUE THREAD

**Issue by blacksun1** [midknight41/map-factory#8]
Perhaps we could look at converting the code to Babel?

Oh, look I already did. https://github.com/blacksun1/map-factory/tree/babel

Totally up to you though if you want to or not.

**Comment by midknight41** [comment]
lol!

**Comment by midknight41** [comment]
You'd find it easier to work in babel I suppose? It doesn't make much difference to me but, I admit, I do rather like working in VS with TypeScript.

**Comment by blacksun1** [comment]
I don't mind, I just want some linting in place. Should we setup some tslint rules then?

**Comment by midknight41** [comment]
You are sooooo OCD. :)

**Comment by blacksun1** [comment]
tslint rules are now in place. I'm happy to close this now.
