### ISSUE TITLE
throws an error when the path in source is not available

### ISSUE THREAD

**Issue by simranjeet2589** [midknight41/map-factory#83]
consider following: -
```
var mapFactory = require("map-factory")

var mapper = mapFactory();

mapper.map("a.b[0].c").to("c").execute({
    "a":  {
    "d": 2
  }
})
```
The above code throws an error: "TypeError: Cannot read property '0' of undefined".

Expected: it should not throw error and should not map anything as well like the usual behaviour of the package.

**Comment by midknight41** [comment]
Fixed in 3.7.1
