### ISSUE TITLE
Why should be mapped object always new?

### ISSUE THREAD

**Issue by bharanidharan-k** [midknight41/map-factory#9]
Why don't we pass destination object as well, so that destination object can be enriched with mapped data? Practically it helps a lot in my use cases.

something like,
map.execute(source, destination);

However, keep supporting map.execute(source);

**Comment by midknight41** [comment]
Makes sense really.

**Comment by midknight41** [comment]
I've added that. Published as v1.1.0

**Comment by blacksun1** [comment]
Good morning Gents and @midknight41,

Maybe.... what happens to the existing object though? @bharanidharan-k sounds like you are suggesting a merge of properties rather than a simple destruction of the old. 

An overload of the existing method does not feel the correct way to go in this case. How about something like a separate merge method such as:

```js
/**
* Maps a source object onto an existing object.
* @parm {object} target - The target object that will receive the new elements.
* @param {object} source - The source object that will be mapped using the mapping object
* @returns {void}
**/
merge(target, source)
```

which might be used like below

```js
const createMapper = require("map-factory");

const fieldSource = {
  "fieldName": "name1",
  "fieldId": "123",
  "fieldDescription": "description"
};

const fieldMap = createMapper();
fieldMap("fieldName");
fieldMap("fieldId");

const cakeSource = {
  "cakeId": "id:cake-chocolate",
  "cakeName": "Chocolate",
  "cakeDescription": "Tahini gives this cake a subtle nutty flavour."
};

const cakeMap = createMapper();
cakeMap("cakeName").to("cake.name");
cakeMap("fieldId").to("cake.id");

const result = map.merge(cakeMap.execute(cakeSource), fieldSource);
console.log(result);

/*
  {
    "fieldName": "name1",
    "fieldId": "123"
  }
*/

const actual2 = {
  fieldName: "Chocolate",
  fieldAddress: "123 Foobar Rd, Foobaz"
};

const result = map.merge(source, actual2);
console.log(result);

/*
{
  "fieldName": "name1",
  "fieldId": "123",
  "fieldAddress": "123 Foobar Rd, Foobaz"
}
*/
```

But I would ask what the use case is? Is it as above? If it is then I would say it might make sense to extend the mapper to accept multiple source items.

Thoughts?


Regards,

**Comment by bharanidharan-k** [comment]
My use case is

1. I get small json objects from different sources
2. I need to keep merging these sources to one json.
So, it is very similar what you explained above.

But, if I have to extend and generalize this use case, the destination json could also be MULTIPLE instead of one.

**Comment by blacksun1** [comment]
What about this?

```js
const createMapper = require("map-factory");

const fieldSource = {
  "fieldName": "name1",
  "fieldId": "123",
  "fieldDescription": "description"
};

const cakeSource = {
  "cakeId": "id:cake-chocolate",
  "cakeName": "Chocolate",
  "cakeDescription": "Tahini gives this cake a subtle nutty flavour."
};

const fieldMap = createMapper();
fieldMap("fieldSource.fieldName").to("fieldName");
fieldMap("fieldSource.fieldId").to("fieldId");
fieldMap("cakeSource.cakeName").to("cake.name");
fieldMap("cakeSource.fieldId").to("cake.id");

const result = map.execute({
  fieldSource: fieldSource,
  cakeSource: cakeSource
});
console.log(result);

/*
{
  "fieldName": "name1",
  "fieldId": "123",
  "fieldAddress": "123 Foobar Rd, Foobaz"
}
*/
```

This way you are not mutating your existing objects.

**Comment by bharanidharan-k** [comment]
Fantastic. This makes more sense and better improvement.  Object literals help in source!

**Comment by blacksun1** [comment]
I think so too.

IRL, assuming ES6 and using Q for promises, I see this working something like this but insert your own favourites,

```js
bringCake() {
  mapper = cakeMapperFactory.create();

  return Q.all([getCakeRecipie, getCakeComments]).
    .spread((recipe, comments) =>mapper.execute({recipe, comments}))
}
```

Regards,

**Comment by midknight41** [comment]
I think both use cases are valid. For merging multiple items this...

```js
map("ingredients.supplier").to("supplier")
map("recipe.creator").to("creator")
map("comments")

map.execute({ingredients, recipe, comments})
``` 
...is what I was thinking too. You can build the source object up any way you like.

I've already added the ```map.execute(source, destination)``` to the module. No point in being prescriptive about how people use it as long as the understand the limitations.

So I don't see any work to do here now. Happy to close this one again?

**Comment by blacksun1** [comment]
We should probably put some documentation around this though. Maybe a
patterns document?

Another issue though I think.

**Comment by midknight41** [comment]
Create issue: https://github.com/midknight41/map-factory/issues/10
