### ISSUE TITLE
A chained mapper is not reusable

### ISSUE THREAD

**Issue by DamianStanger** [midknight41/map-factory#91]
When using the chain method it seems that you cant reuse the mapper again.

```
  describe("when chain is called twice", () => {
    it("one call should not effect the other", done => {
      secondaryMapper.map("foo").to("bar");
      const actual1 = mapper("foo").chain(secondaryMapper).execute(source);
      expect(actual1).to.equal(expected);
      const actual2 = mapper("foo").chain(secondaryMapper).execute(source);
      expect(actual2).to.equal(expected);
      done();
    });
  });
```

the line ```expect(actual2).to.equal(expected);``` fails with the error:
```
Expected {} to equal specified value: { bar: 'bar' }
at /mnt/c/_stuff/code/github/map-factory/dist/test/chain-test.js:67:37
```

It was my understanding that you should be able to create a mapper then use it multiple times, unless im doing something wrong it looks like you cant do that when using the chain method.

**Comment by midknight41** [comment]
`chain` mutates the mapper so setting `chain(secondaryMapper)`  once is sufficient.

```js
describe("when chain is called twice", () => {
    it("one call should not effect the other", done => {
      secondaryMapper.map("foo").to("bar");
      const actual1 = mapper("foo").chain(secondaryMapper).execute(source); // mutates mapper
      expect(actual1).to.equal(expected);
      const actual2 = mapper.execute(source); // secondaryMapper will be applied here.
      expect(actual2).to.equal(expected);
      done();
    });
  });
```

**Comment by DamianStanger** [comment]
I think i was imagining it was more like an immutable builder pattern where the thing returned is a new instance of the thing. I had not really considered that it would be mutating the mapper in place. It makes sense when you put it in those terms. But from a users perspective (one not familiar with internals) it was a little confusing when putting the whole thing into one line that returns the mapped result.
Given this example (forgive typos ive typed straight into this text box)
```
var mapper1 = createMapper().map("foo");
var result1 = mapper1.execute(input);
var mapper2 = mapper1.chain(secondaryMapper);
var result2 = mapper2.execute(input);
var result3 = mapper1.execute(input);
```
I now know that result2 === result3 !== result1
but i expected it to be result1 === result3 !== result2

this is because of the way chaining calls mutates the mapper.
As you said its not wrong, it was just unclear especially when you put it all together thus:
```
var mapper1 = createMapper().map("foo");
var result1 = mapper1.execute(input);
var result2 = mapper1.chain(secondaryMapper).execute(input);
var result3 = mapper1.execute(input);
```
again result2 === result3 !=== result1

Is my understanding correct?

**Comment by midknight41** [comment]
That is correct. I'll update the docs to make it more clear.
