### ISSUE TITLE
How to append additional fields in each object in an array

### ISSUE THREAD

**Issue by sahas-** [midknight41/map-factory#93]
This may be just a documentation enhancement. Is it possible to append additional fields across all the objects in a result array?

**Comment by simranjeet2589** [comment]
@sahas- Could you please provide an example?

**Comment by sahas-** [comment]
@simranjeet2589 

Source is an array of objects.
Below mapping helps me to transform the entire array.

 mapper
                    .map("message[].streetAddress1").to("[].address.address1")
                    .map("message[].streetAddress2").to("[].address.address2")

I want to append an additional field in each object, e.g. name.

mapper. set() will append the field in one object. How to append this field across the array ?

**Comment by simranjeet2589** [comment]
@sahas- Considering following is the source
```javascript
const source = [{
  "message": [{
    "streetAddress1": "foo",
    "streetAddress2": "bar"
  }]
}, {
  "message": [{
    "streetAddress1": "foo1",
    "streetAddress2": "bar1"
  }]
}]
```

If we change the mapper to the following, the output result will include name in all the object.
```javascript
mapper
.map("message[].streetAddress1").to("[].address.address1")
.map("message[].streetAddress2").to("[].address.address2")
.set("[].name", "test");

const ouput = mapper.each(source);
//output will look like

[{
  "address": {
    "address1": "foo",
    "address2": "bar"
  },
  "name": "test"
}, {
  "address": {
    "address1": "foo1",
    "address2": "bar1"
  },
  "name": "test"
}]
```
Please let me know if this is what you are looking for or if there is something I can help you with.
